[package]
name = "pi_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1"
winit = { version = "0.26", default-features = false, features = ["x11"] }

[target.'cfg(windows)'.dependencies]
raw-gl-context = "0.1"